name: "t212"
version: "1.0.0"
profile: "t212"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

seeds:
  +schema: raw

models:
  t212:
    stg:
      +schema: stg
      +materialized: view
    int:
      +schema: int
      +materialized: table
    marts:
      +schema: marts
      +materialized: table